### ISSUE TITLE
Implement the ability to handle "unlimited" limits for features.

### ISSUE THREAD

**Issue by rennokki** [rennokki/plans#13]
This feature request came from: https://www.reddit.com/r/laravel/comments/8vkf5w/laravel_plans_one_easy_way_to_manage_plans_for/e1pofwz/

Basically, when you are giving unlimited amount of a certain `limit` feature, you expect everytime `consumeFeature()` to never actually waste from an amount.

**Comment by fgilio** [comment]
Hi @rennokki!
This looks nice. I've only looked at the code from the MR and from my phone, so I might be wrong. But, this won't actually log any usage, right?
I was thinking that it would be really useful to know how much of a feature has been used, even if there's no limit.

**Comment by rennokki** [comment]
@fgilio Indeed, tracking usage is the root of all solutions for anyone. I have commited the changes, this will be a better fit for the feature.

**Comment by fgilio** [comment]
Awesome!
I really like how this is evolving. I had to develop something similar, and tbh I'd just used this if only it was available at the time. It even has some considerations that I overlooked 🤦‍♂️

Congrats for the quality work and thanks for open sourcing it :D
