### ISSUE TITLE
Payment Systems

### ISSUE THREAD

**Issue by grafikkaos** [rennokki/plans#15]
Hi,

Thanks for this great package.  It will save me a fair bit of time trying to roll out my own solution. However, how easy would it be to combine this package with payment systems such as Stripe, Paypal or SecurionPay?  Especially considering Stripe and SecurionPay have webhooks that developers can tie into?

Thanks

Emmanuel

**Comment by rennokki** [comment]
Hi @grafikkaos,

I'm glad the package is a great solution for you. :smile: 

Currently, the package was rolled out without payment systems integrated. Luckily, it seems like great feature and it surely will be implemented. I have seen that Laravel Cashier does that with Stripe, so i'll take a look at the source code for Cashier and try to implement a solution in Laravel Plans.

I have checked out SecurionPay, it seems like a reasonable choice to implement Stripe-alike payments, and this comes in help for countries that doesn't support Stripe.

This is a great feature request! Thank you for your feedback!

**Comment by grafikkaos** [comment]
Awesome....  Will be keeping my eye on this one 👍

**Comment by rokde** [comment]
Is it possible to support Laravel Cashier instead of your own solution? Maybe a direct bridge to your plans or something like this.?

**Comment by rennokki** [comment]
That would be good. An adapter should work well. But i will have to address the problem of implementing PayPal subscriptions or Securion, which aren't supprted.

Maybe if i build my own abstractisation will work better & would be cleaner?

**Comment by willmkt** [comment]
It would be easer to use a solution like Omnipay,

https://github.com/thephpleague/omnipay#payment-gateways
https://github.com/overtrue/laravel-payment

**Comment by rennokki** [comment]
@willmkt Seems like a good module which i can try over Laravel Cashier, since Cashier already does its job and Omnipay is based on payments only.

**Comment by rennokki** [comment]
Stripe is the only supported service right now, lookin forward to implementing more, but that's the only i can provide now. All changes are in https://github.com/rennokki/plans/pull/30

There are changes on tables & events, so review that before upgrading.

Version 1.5.0 is published with Stripe integrated, check the readme.
This still needs very much testing on the recurrency & payment parts (even if unit tests are passed), so don't be afraid to signal issues with it.
