### ISSUE TITLE
Scheduling renewSubscription cron command without downtime

### ISSUE THREAD

**Issue by AlexGodbehere** [rennokki/plans#49]
Great package, thanks!

How would I ensure that a user has no 'downtime' in their subscription when using cron to renew? If I purchased a subscripton at 6pm on the 1st of the month and the cron commnd runs once a day, then I'd have to wait until midnight on the 1st of the next month to have my subscription renewed. This way, I would have 6 hours of not being a premium user.

Is there a way around this or am I misunderstanding how the cron command should be set up?

**Comment by rennokki** [comment]
The ideal solution would be a checkup for an active subscription with a delay, which can be passed. This might be better, so i'll have to implement it.
