### ISSUE TITLE
Quetions

### ISSUE THREAD

**Issue by drkwolf** [rennokki/plans#54]
Hi, i'was looking into the code (HasPlans), and i've found this peace of code that looks like a bug,

```php
    public function extendCurrentSubscriptionUntil($date, bool $startFromNow = true, bool $isRecurring = true) {
.....
        $subscription = config('plans.models.subscription')::create([
            'plan_id' => $activeSubscription->id, /// should be ->plan_id
        ]);
```
the same code is used   ```extendCurrentSubscriptionWith```.

also i was wondering why you use model:create instead of $this->subscription->save(...) as done in the other methods ?

**Comment by smartified** [comment]
i think the reasoning is that extend should only happen inside the currently active plan and not just any plan needed.

**Comment by rennokki** [comment]
Release: https://github.com/rennokki/plans/releases/tag/1.6.3
