### ISSUE TITLE
Question about plans

### ISSUE THREAD

**Issue by movepixels** [rennokki/plans#55]
I will try to explain so the idea of what I am trying to do makes sense.
Scenario: I register as a user and I want to add 5 listings / advertisements to the site and the site does not have a 5 Ad feature so I buy 5 individual plans. 
Basically can a user have multiple subscriptions of identical plans?

Thanks,
Dave

**Comment by rennokki** [comment]
Well, the fact that the relationship `activeSubscriptions()` exists, it's like shooting yourself in the leg to do this. Instead, try using `Features` and use them to track the usage.

**Comment by movepixels** [comment]
I think you misunderstand the question. I understand the features aspect. But User want to subscribe to PlanA (basic ad, with minimal features) but also say have 2 premium PlanB ads at the same time. Each plan has its features yes but to have multiple active "Plans / Subscriptions" for the user? Thats what I was wondering.
